/**
 * Sidecar installer for node-llama-cpp.
 *
 * When running from a compiled binary, node-llama-cpp can't be loaded
 * in-process because bun's compiled binary doesn't resolve transitive
 * dependencies for dynamically imported external packages.
 *
 * Instead, we install node-llama-cpp to ~/.mdg/node_modules/ and create
 * an embed-server.js script that the compiled binary spawns as a subprocess.
 * Communication happens via newline-delimited JSON over stdin/stdout.
 */
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { platform, arch } from "node:process";
import { homedir } from "node:os";
import { execSync } from "node:child_process";

const MDG_DIR = join(homedir(), ".mdg");
const MDG_NODE_MODULES = join(MDG_DIR, "node_modules");

/** The version of node-llama-cpp to install */
const LLAMA_CPP_VERSION = "3.18.1";

export function getMdgDir(): string {
  return MDG_DIR;
}

export function getEmbedServerPath(): string {
  return join(MDG_DIR, "embed-server.js");
}

/**
 * Determine the platform-specific optional dependency name.
 */
function getPlatformPackage(): string {
  const os = platform;
  const cpu = arch;

  const platformMap: Record<string, Record<string, string[]>> = {
    darwin: {
      arm64: ["@node-llama-cpp/mac-arm64-metal"],
      x64: ["@node-llama-cpp/mac-x64"],
    },
    linux: {
      x64: ["@node-llama-cpp/linux-x64"],
      arm64: ["@node-llama-cpp/linux-arm64"],
      arm: ["@node-llama-cpp/linux-armv7l"],
    },
    win32: {
      x64: ["@node-llama-cpp/win-x64"],
      arm64: ["@node-llama-cpp/win-arm64"],
    },
  };

  const packages = platformMap[os]?.[cpu];
  if (!packages || packages.length === 0) {
    throw new Error(
      `Unsupported platform: ${os}-${cpu}. ` +
        `Cannot auto-install node-llama-cpp native bindings.`
    );
  }

  return packages[0]!;
}

/**
 * Check if node-llama-cpp sidecar is properly installed.
 */
export function isSidecarInstalled(): boolean {
  const llamaPkgJson = join(
    MDG_NODE_MODULES,
    "node-llama-cpp",
    "package.json"
  );
  if (!existsSync(llamaPkgJson)) return false;

  try {
    const pkg = JSON.parse(readFileSync(llamaPkgJson, "utf8"));
    if (pkg.version !== LLAMA_CPP_VERSION) return false;
  } catch {
    return false;
  }

  // Also check that embed-server.js exists
  return existsSync(getEmbedServerPath());
}

/**
 * Find a working package manager. Prefer bun, then npm.
 */
function findPackageManager(): { cmd: string; name: string } {
  try {
    execSync("bun --version", { stdio: "ignore" });
    return { cmd: "bun", name: "bun" };
  } catch {}

  try {
    execSync("npm --version", { stdio: "ignore" });
    return { cmd: "npm", name: "npm" };
  } catch {}

  throw new Error(
    "Neither bun nor npm found in PATH. " +
      "Please install bun (https://bun.sh) or Node.js, " +
      "then run `mdg grep --semantic` again."
  );
}

/**
 * Find the bun binary path for spawning the embed server.
 */
export function findBunPath(): string {
  try {
    return execSync("which bun", { encoding: "utf8" }).trim();
  } catch {}

  // Common locations
  const candidates = [
    join(homedir(), ".bun", "bin", "bun"),
    "/usr/local/bin/bun",
    "/opt/homebrew/bin/bun",
  ];

  for (const p of candidates) {
    if (existsSync(p)) return p;
  }

  throw new Error(
    "bun not found in PATH. The embed server requires bun to run.\n" +
      "Install bun: https://bun.sh"
  );
}

/**
 * The embed-server.js script content.
 *
 * This script is installed to ~/.mdg/embed-server.js and run via `bun`.
 * It loads node-llama-cpp from the local node_modules, initializes the
 * embedding model, and accepts JSON-RPC requests over stdin.
 *
 * Protocol (newline-delimited JSON):
 *   Request:  { "id": 1, "method": "init", "params": { "modelUri": "...", "modelsDir": "..." } }
 *   Request:  { "id": 2, "method": "embed", "params": { "texts": [...], "type": "document", "titles": [...] } }
 *   Request:  { "id": 3, "method": "dimensions" }
 *   Request:  { "id": 4, "method": "modelId" }
 *   Request:  { "id": 5, "method": "dispose" }
 *   Response: { "id": 1, "result": ... } or { "id": 1, "error": "..." }
 */
function getEmbedServerScript(): string {
  return `#!/usr/bin/env bun
// mdg embed-server — IPC embedding service
// Auto-generated by mdg. Do not edit.
import { getLlama, LlamaLogLevel, resolveModelFile } from "node-llama-cpp";
import { createInterface } from "node:readline";

let llama = null;
let model = null;
let context = null;
let dimensions = null;
let modelUri = "";

function isQwen3Model(uri) {
  return /qwen.*embed/i.test(uri) || /embed.*qwen/i.test(uri);
}

function formatForEmbedding(text, type, title) {
  if (isQwen3Model(modelUri)) {
    if (type === "query") {
      return \`Instruct: Retrieve relevant documents for the given query\\nQuery: \${text}\`;
    }
    return title ? \`\${title}\\n\${text}\` : text;
  }
  if (type === "query") {
    return \`task: search result | query: \${text}\`;
  }
  return title ? \`title: \${title} | text: \${text}\` : \`text: \${text}\`;
}

function respond(id, result) {
  process.stdout.write(JSON.stringify({ id, result }) + "\\n");
}

function respondError(id, error) {
  process.stdout.write(JSON.stringify({ id, error: String(error) }) + "\\n");
}

async function handleRequest(msg) {
  const { id, method, params } = msg;

  try {
    switch (method) {
      case "init": {
        modelUri = params.modelUri;
        llama = await getLlama({ logLevel: LlamaLogLevel.error });
        const modelPath = await resolveModelFile(params.modelUri, params.modelsDir);
        model = await llama.loadModel({ modelPath });
        context = await model.createEmbeddingContext();
        const testEmbed = await context.getEmbeddingFor("test");
        dimensions = testEmbed.vector.length;
        respond(id, { dimensions, modelUri });
        break;
      }

      case "embed": {
        const { texts, type, titles } = params;
        const results = [];
        const batchSize = 32;
        for (let i = 0; i < texts.length; i += batchSize) {
          const batch = texts.slice(i, i + batchSize);
          const batchTitles = titles ? titles.slice(i, i + batchSize) : undefined;
          const promises = batch.map(async (text, j) => {
            const title = batchTitles ? batchTitles[j] : undefined;
            const formatted = formatForEmbedding(text, type, title);
            const result = await context.getEmbeddingFor(formatted);
            return Array.from(result.vector);
          });
          const batchResults = await Promise.all(promises);
          results.push(...batchResults);
        }
        respond(id, results);
        break;
      }

      case "dimensions": {
        respond(id, dimensions);
        break;
      }

      case "modelId": {
        respond(id, modelUri);
        break;
      }

      case "dispose": {
        if (context) { await context.dispose(); context = null; }
        if (model) { await model.dispose(); model = null; }
        if (llama) { await llama.dispose(); llama = null; }
        respond(id, true);
        process.exit(0);
        break;
      }

      default:
        respondError(id, \`Unknown method: \${method}\`);
    }
  } catch (e) {
    respondError(id, e.message || String(e));
  }
}

// Signal readiness
process.stdout.write(JSON.stringify({ ready: true }) + "\\n");

const rl = createInterface({ input: process.stdin });
rl.on("line", (line) => {
  try {
    const msg = JSON.parse(line);
    handleRequest(msg);
  } catch (e) {
    process.stdout.write(JSON.stringify({ id: null, error: \`Parse error: \${e.message}\` }) + "\\n");
  }
});

// Keep alive
process.stdin.resume();
`;
}

/**
 * Install node-llama-cpp and the embed server to ~/.mdg/.
 */
export async function installSidecar(
  onProgress?: (msg: string) => void
): Promise<void> {
  const log = onProgress ?? console.log;

  if (!existsSync(MDG_DIR)) {
    mkdirSync(MDG_DIR, { recursive: true });
  }

  const platformPkg = getPlatformPackage();
  const pm = findPackageManager();

  log(`Installing node-llama-cpp for semantic search (one-time setup)...`);
  log(`  Platform package: ${platformPkg}`);
  log(`  Installing to: ${MDG_DIR}`);
  log(`  Using: ${pm.name}`);

  // Create a minimal package.json
  const sidecarPkg = {
    name: "mdg-sidecar",
    version: "0.0.1",
    private: true,
    dependencies: {
      "node-llama-cpp": LLAMA_CPP_VERSION,
      [platformPkg]: LLAMA_CPP_VERSION,
    },
    trustedDependencies: ["node-llama-cpp"],
  };

  writeFileSync(
    join(MDG_DIR, "package.json"),
    JSON.stringify(sidecarPkg, null, 2)
  );

  // Run install
  const installCmd =
    pm.name === "bun"
      ? `bun install --no-save`
      : `npm install --no-save --ignore-scripts=false`;

  try {
    log(`  Running ${pm.name} install...`);
    execSync(installCmd, {
      cwd: MDG_DIR,
      stdio: ["ignore", "pipe", "pipe"],
      timeout: 120_000,
      env: {
        ...process.env,
        npm_config_ignore_scripts: "false",
      },
    });
  } catch (e: any) {
    const errorMsg = e.stderr?.toString() || e.message;
    throw new Error(
      `Failed to install node-llama-cpp:\n${errorMsg}\n\n` +
        `You can install manually:\n` +
        `  cd ~/.mdg && ${pm.name} add node-llama-cpp@${LLAMA_CPP_VERSION} ${platformPkg}@${LLAMA_CPP_VERSION}`
    );
  }

  // Write the embed server script
  const serverPath = getEmbedServerPath();
  writeFileSync(serverPath, getEmbedServerScript());
  log(`  Embed server written to: ${serverPath}`);
  log(`  Done! node-llama-cpp installed successfully.`);
}
